/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.hotelalura.hotelchallenge.igu;

import ar.hotelalura.hotelchallenge.logica.Controladora;
import ar.hotelalura.hotelchallenge.logica.Huesped;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Juan Bravo
 */
public class PantallaRegistroHuspedesMod extends javax.swing.JFrame {

     int xMouse, yMouse;
     
     Controladora control = new Controladora();
     PantallaReservas reservas = new PantallaReservas();
     Mensaje mensajeError = null;
     Huesped huesped;
     int idHuesped;
     int numReserva;
     private Date checkIn;
     private Date checkOut;
     private double valor;
     private String formaPago;
     
     public void setDatos(Date checkIn, Date checkOut, double valor, String formaPago){
            this.checkIn = checkIn;
            this.checkOut = checkOut;
            this.valor = valor;
            this.formaPago = formaPago;
            
     }
   
     
     public PantallaRegistroHuspedesMod(int numReserva, int numHuesped) {
         
        initComponents();
        FlatMaterialLighterIJTheme.setup();
        control = new Controladora();
        InputNacimiento.setMaxSelectableDate(new Date());
        this.idHuesped = numHuesped;
        this.numReserva = numReserva;
        cargarDatos(idHuesped);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        btnAtras = new javax.swing.JPanel();
        txtAtras = new javax.swing.JLabel();
        imgIcono = new javax.swing.JLabel();
        imgRegistro = new javax.swing.JLabel();
        panelDerecho = new javax.swing.JPanel();
        txtRegistro = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        InputTelefono = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        InputNombre = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        InputNacimiento = new com.toedter.calendar.JDateChooser();
        InputApellido = new javax.swing.JTextField();
        txtApellido = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JLabel();
        ComBoxNacionalidad = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JPanel();
        txtGuardar = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzquierdo.setBackground(new java.awt.Color(14, 139, 199));

        btnAtras.setBackground(new java.awt.Color(14, 139, 199));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAtras.setBackground(new java.awt.Color(0, 0, 0));
        txtAtras.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txtAtras.setForeground(new java.awt.Color(255, 255, 255));
        txtAtras.setText("<");
        txtAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtrasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtAtras)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtrasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgIcono.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Bravo\\Desktop\\HotelChallenge2\\src\\imagenes\\Ha-100px.png")); // NOI18N

        imgRegistro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Bravo\\Desktop\\HotelChallenge2\\src\\imagenes\\registro.png")); // NOI18N

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(imgRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(imgIcono))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgRegistro)
                .addGap(14, 14, 14))
        );

        background.add(panelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelDerecho.setBackground(new java.awt.Color(255, 255, 255));

        txtRegistro.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txtRegistro.setForeground(new java.awt.Color(14, 139, 199));
        txtRegistro.setText("EDICION REGISTRO HUÉSPED");

        jSeparator7.setBackground(new java.awt.Color(14, 139, 199));
        jSeparator7.setForeground(new java.awt.Color(14, 139, 199));

        InputTelefono.setBackground(new java.awt.Color(255, 255, 255));
        InputTelefono.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        InputTelefono.setText("Ingrese su telefono");
        InputTelefono.setBorder(null);
        InputTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputTelefonoMouseClicked(evt);
            }
        });
        InputTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputTelefonoKeyTyped(evt);
            }
        });

        txtNacionalidad.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtNacionalidad.setForeground(new java.awt.Color(102, 102, 102));
        txtNacionalidad.setText("NACIONALIDAD");

        jSeparator4.setBackground(new java.awt.Color(14, 139, 199));
        jSeparator4.setForeground(new java.awt.Color(14, 139, 199));

        jSeparator3.setBackground(new java.awt.Color(14, 139, 199));
        jSeparator3.setForeground(new java.awt.Color(14, 139, 199));

        InputNombre.setBackground(new java.awt.Color(255, 255, 255));
        InputNombre.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        InputNombre.setText("Ingrese su nombre");
        InputNombre.setBorder(null);
        InputNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputNombreMouseClicked(evt);
            }
        });
        InputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputNombreKeyTyped(evt);
            }
        });

        txtFechaNacimiento.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        txtFechaNacimiento.setText("FECHA DE NACIMIENTO");

        txtNombre.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("NOMBRE");

        jSeparator5.setBackground(new java.awt.Color(14, 139, 199));
        jSeparator5.setForeground(new java.awt.Color(14, 139, 199));

        InputNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        InputNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        InputNacimiento.setDateFormatString("yyyy-MM-dd");
        InputNacimiento.setInheritsPopupMenu(true);

        InputApellido.setBackground(new java.awt.Color(255, 255, 255));
        InputApellido.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        InputApellido.setText("Ingrese su apellido");
        InputApellido.setBorder(null);
        InputApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputApellidoMouseClicked(evt);
            }
        });
        InputApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputApellidoKeyTyped(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("APELLIDO");

        jSeparator6.setBackground(new java.awt.Color(14, 139, 199));
        jSeparator6.setForeground(new java.awt.Color(14, 139, 199));

        txtTelefono.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setText("TELEFONO");

        ComBoxNacionalidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        ComBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "afgano-afgana ", "alemán, alemana ", "árabe-árabe ", "argentino-argentina ", "australiano-australiana ", "belga-belga ", "boliviano-boliviana ", "brasileño-brasileña ", "camboyano-camboyana ", "canadiense-canadiense ", "chileno-chilena ", "chino-china ", "colombiano-colombiana ", "coreano-coreana ", "costarricense-costarricense ", "cubano-cubana ", "danés-danesa ", "ecuatoriano-ecuatoriana ", "egipcio-egipcia ", "salvadoreño-salvadoreña ", "escocés-escocesa ", "español-española ", "estadounidense-estadounidense", "estonio-estonia", "etiope-etiope ", "filipino-filipina ", "finlandés-finlandesa ", "francés-francesa ", "galés-galesa ", "griego-griega ", "guatemalteco-guatemalteca ", "haitiano-haitiana ", "holandés-holandesa ", "hondureño-hondureña ", "indonés-indonesa ", "inglés-inglesa ", "iraquí-iraquí ", "iraní-iraní ", "irlandés-irlandesa ", "israelí-israelí ", "italiano-italiana ", "japonés-japonesa ", "jordano-jordana ", "laosiano-laosiana ", "letón-letona ", "letonés-letonesa ", "malayo-malaya ", "marroquí-marroquí", "mexicano-mexicana ", "nicaragüense-nicaragüense ", "noruego-noruega ", "neozelandés-neozelandesa ", "panameño-panameña ", "paraguayo-paraguaya ", "peruano-peruana ", "polaco-polaca ", "portugués-portuguesa ", "puertorriqueño-puertorriqueño ", "dominicano-dominicana ", "rumano-rumana ", "ruso-rusa ", "sueco-sueca ", "suizo-suiza ", "tailandés-tailandesa ", "taiwanes-taiwanesa ", "turco-turca", "ucraniano-ucraniana", "uruguayo-uruguaya ", "venezolano-venezolana ", "vietnamita-vietnamita" }));

        btnGuardar.setBackground(new java.awt.Color(14, 139, 199));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        txtGuardar.setBackground(new java.awt.Color(14, 139, 199));
        txtGuardar.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        txtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        txtGuardar.setText("  GUARDAR EDICION");
        txtGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addComponent(txtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistro)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addComponent(txtRegistro)
                .addGap(52, 52, 52)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(InputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(InputNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ComBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(InputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        background.add(panelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 60, 440, 634));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSuperiorMouseDragged(evt);
            }
        });
        panelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSuperiorMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        txtExit.setBackground(new java.awt.Color(0, 0, 0));
        txtExit.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtExit)
                .addGap(28, 28, 28))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtExit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseClicked
        PantallaReservasMod reservasMod = new PantallaReservasMod(numReserva,idHuesped);
        reservasMod.setVisible(true);
        reservasMod.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtAtrasMouseClicked

    private void txtAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseEntered
        txtAtras.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtAtrasMouseEntered

    private void txtAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseExited
        txtAtras.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_txtAtrasMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered

        txtExit.setForeground(new Color(14,139,199));
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited

        txtExit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtExitMouseExited

    private void panelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelSuperiorMouseDragged

    private void panelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelSuperiorMousePressed

    private void txtGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGuardarMouseClicked
         
         String nombre = InputNombre.getText();
         String apellido = InputApellido.getText();
         Date fechaNacimiento = InputNacimiento.getDate();
         String nacionalidad = (String) ComBoxNacionalidad.getSelectedItem();
         String telefono = InputTelefono.getText();
         
         if(nombre.isEmpty() || apellido.isEmpty() || fechaNacimiento == null || nacionalidad.isEmpty() || telefono.isEmpty()){
            mensajeError = new Mensaje("ADVERTENCIA","Debe completar todos los campos para continuar.");
            mensajeError.setVisible(true);
            mensajeError.setLocationRelativeTo(null);
         
         }else{
            Date nacimiento = reservas.convertirFecha(fechaNacimiento);
            control.modificar(huesped,nombre, apellido, telefono,nacimiento,nacionalidad,checkIn,checkOut,valor,formaPago);
            
            PantallaBusqueda busqueda = new PantallaBusqueda();
            busqueda.cargarTablaHuespedes();
            busqueda.cargarTablaReservas();
            busqueda.setVisible(true);
            busqueda.setLocationRelativeTo(null);
            mensajeError = new Mensaje("EXITO","Edicion Completada");
                        
            mensajeError.setVisible(true);
            mensajeError.setLocationRelativeTo(null); 
        
        this.dispose();
             
         }

    }//GEN-LAST:event_txtGuardarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        
        
        
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void InputNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputNombreMouseClicked
       InputNombre.setText("");
    }//GEN-LAST:event_InputNombreMouseClicked

    private void InputApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputApellidoMouseClicked
        InputApellido.setText("");
    }//GEN-LAST:event_InputApellidoMouseClicked

    private void InputTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputTelefonoMouseClicked
        InputTelefono.setText("");
    }//GEN-LAST:event_InputTelefonoMouseClicked

    private void InputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNombreKeyTyped
       if(!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)){
       evt.consume();
         }
    }//GEN-LAST:event_InputNombreKeyTyped

    private void InputTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTelefonoKeyTyped
        int key = evt.getKeyChar();
        
        boolean numeros = key >=48 && key<=57;
        
        if(!numeros){
            evt.consume();
         }
    }//GEN-LAST:event_InputTelefonoKeyTyped

    private void InputApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputApellidoKeyTyped
        if(!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)){
       evt.consume();
        }
    }//GEN-LAST:event_InputApellidoKeyTyped

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBoxNacionalidad;
    private javax.swing.JTextField InputApellido;
    public com.toedter.calendar.JDateChooser InputNacimiento;
    private javax.swing.JTextField InputNombre;
    private javax.swing.JTextField InputTelefono;
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel imgIcono;
    private javax.swing.JLabel imgRegistro;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtAtras;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtGuardar;
    private javax.swing.JLabel txtNacionalidad;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRegistro;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables

         private void cargarDatos(int idHuesped) {
         this.huesped = control.traerHuesped(idHuesped);
         InputNombre.setText(huesped.getNombre());
         InputApellido.setText(huesped.getApellido());
         InputNacimiento.setDate(huesped.getfNacimiento());
         InputTelefono.setText(huesped.getTelefono());
    }
}
